-- migrate:up
-- Esquema base de contabilidad

CREATE TABLE accounts (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('activo', 'pasivo', 'patrimonio', 'ingresos', 'egresos')),
    code TEXT NOT NULL UNIQUE,
    normal_side TEXT NOT NULL CHECK (normal_side IN ('debe', 'haber')),
    extra_data JSONB,
    parent_id INT REFERENCES accounts(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE banks (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE credit_cards (
    id SERIAL PRIMARY KEY,
    bank_id INT REFERENCES banks(id),
    name TEXT NOT NULL,
    account_hnl_id INT REFERENCES accounts(id),
    account_usd_id INT REFERENCES accounts(id),
    holder_name TEXT,
    last_digits VARCHAR(8),
    is_active BOOLEAN NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE email_transactions (
    id SERIAL PRIMARY KEY,
    email_id TEXT NOT NULL,
    business_name TEXT NOT NULL,
    amount NUMERIC(14,2) NOT NULL,
    transaction_date DATE NOT NULL,
    processed BOOLEAN DEFAULT FALSE,
    currency TEXT NOT NULL CHECK (currency IN ('USD', 'HNL')),
    card_id INT REFERENCES credit_cards(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE usd_exchange_rates (
    id SERIAL PRIMARY KEY,
    rate NUMERIC(14,4) NOT NULL,
    effective_date DATE NOT NULL UNIQUE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE transactions (
    id SERIAL PRIMARY KEY,
    description TEXT,
    reference TEXT,
    date DATE NOT NULL,
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE journals (
    id SERIAL PRIMARY KEY,
    journal_number BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2600000 INCREMENT BY 10) UNIQUE,
    transaction_id INT REFERENCES transactions(id),
    description TEXT,
    date DATE NOT NULL,
    statement TEXT,
    bank_statement TEXT,
    metadata JSONB,
    email_transaction_id INT REFERENCES email_transactions(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE journal_entries (
    id SERIAL PRIMARY KEY,
    journal_id INT NOT NULL REFERENCES journals(id),
    account_id INT NOT NULL REFERENCES accounts(id),
    amount NUMERIC(14,2) NOT NULL CHECK (amount >= 0),
    side TEXT NOT NULL CHECK (side IN ('debe', 'haber')),
    description TEXT,
    reference TEXT,
    metadata JSONB,
    exchange_rate_id INT REFERENCES usd_exchange_rates(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE tags (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    side TEXT NOT NULL CHECK (side IN ('debe', 'haber')),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE entry_tags (
    entry_id INT NOT NULL REFERENCES journal_entries(id),
    tag_id INT NOT NULL REFERENCES tags(id),
    PRIMARY KEY (entry_id, tag_id)
);

-- migrate:down
DROP TABLE entry_tags;
DROP TABLE tags;
DROP TABLE journal_entries;
DROP TABLE journals;
DROP TABLE transactions;
DROP TABLE usd_exchange_rates;
DROP TABLE email_transactions;
DROP TABLE credit_cards;
DROP TABLE banks;
DROP TABLE accounts;
