services:
  postgrest:
    image: postgrest/postgrest
    container_name: finance_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: ${DATABASE_URL}
      PGRST_DB_SCHEMA: "public"
      PGRST_DB_ANON_ROLE: "web_anon"
      PGRST_SERVER_PORT: "3000"
      PGRST_JWT_SECRET: ${JWT_SECRET}

  dbmate:
    image: amacneil/dbmate:2.13.0
    container_name: finance_dbmate
    working_dir: /
    volumes:
      - ./db:/db
      - ./init:/init
    env_file: .env
    command: ["--wait", "up"]

volumes:
  db_data:
